name: LLMs 
on:
  workflow_dispatch: null
  push:
    paths: ['llm-clients/*']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    # For biggish images, github actions runs out of disk space.
      - name: cleanup disk space
        run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        run: docker build llm-clients --tag ghcr.io/schmidtdse/llm:latest
      - name: Publish
        run: docker push ghcr.io/schmidtdse/llm:latest

